### ISSUE TITLE
Focus not set when replying to really long post

### ISSUE THREAD

**Issue by stodge** [TheBLVD/mammoth#144]
**To Reproduce**
1. Locate a post that is several hundreds of characters long, really really long
2. Tap to reply
3. The app doesn’t automatically set input focus to the reply
4. You have to scroll way down to find the reply input and tap to set focus
5. When typing a reply, with each character entered, the app quickly jumps back to the top of the original post, and then quickly back down to where your cursor is. So you can’t see what you’re typing

**Expected behavior**
The app should set the focus to the input, as it does for shorter posts. It shouldn’t jump up and down the page as you type

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 16.6.1
 - Version: 1.10.2 build 252

**Additional context**

**Comment by bvon** [comment]
I see you're on the official App Store release, and while this bug is very annoying, it's fixed in the current beta which should be shipped to the App Store relatively soon!

**Comment by derspyy** [comment]
still happens to me on latest.
https://github.com/TheBLVD/mammoth/assets/65043391/322463ff-96d8-4a91-b551-524489558fb7
