### ISSUE TITLE
Embedded Links

### ISSUE THREAD

**Issue by Mings-01** [TheBLVD/mammoth#145]
When a link is inserted into a toot using the following as an example no link appears in the post

a href="https://toot.cat/@Hashtags/110413232137598971">Animals, Plants & Fungi</a

<a href="https://toot.cat/@Hashtags/110413232137598971">Animals, Plants & Fungi</a>

**To Reproduce**
1. Go to 'https://toot.cat/@Hashtags/110460687230583361'
2. Tap on ‘can’t tap on because don’t appear'
3. Scroll down to 'Animals, Plants & Fungi'
4. See error ‘There is no link’

**Expected behavior**
Expect links to appear that can be clicked on

**Screenshots**
The first is from Mammoth the second from Metatext
![BE99376D-477A-4712-926E-5254A5077C25](https://github.com/TheBLVD/mammoth/assets/139313407/276bab8b-d40e-4b48-a376-779f773c507c)
![66477BC6-B13A-4732-BB49-971712D477D3](https://github.com/TheBLVD/mammoth/assets/139313407/e93758e4-b362-4391-ad54-024b3d0257df)

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS15.7.8
 - Version 4.1.4

**Additional context**
Posting Indexes that rely on links means the App is useless to me without the ability to link

**Comment by bvon** [comment]
Hey, sorry for the late response, but are you using the Apple Store release or TestFlight version? I believe this issue is fixed in the beta, and I'll check with the team to make sure.

**Comment by derspyy** [comment]
it's even missing text now:

![image](https://github.com/TheBLVD/mammoth/assets/65043391/97f84d3a-886d-417a-b2c3-e7d73df0c4b2)

![image](https://github.com/TheBLVD/mammoth/assets/65043391/90663690-47df-4e2b-8f91-6ea29d1c041b)

**Comment by Mings-01** [comment]
I am on iPhone Version 15.8 now and the problem still occurs on the most recent version of Mammoth I’ve downloaded - Version 2.1 Build 359. Also of note is that link addresses do not always show up, which is a problem when there is a link in your toot if quoting another post - see attached for same post from Tooot and Mammoth
![9366344A-CF5D-446F-92E4-231FAA792596](https://github.com/TheBLVD/mammoth/assets/139313407/01f6c539-d9c0-4bdd-a4d7-b36f26c32e10)
![A99CA809-91EC-48BF-926D-C137CF49A6D9](https://github.com/TheBLVD/mammoth/assets/139313407/606b0710-10f6-4b60-a644-458ce00d974a)

**Comment by Mings-01** [comment]
To answer your question, the Apple Store release and most recent version

**Comment by derspyy** [comment]
seems to be mostly working, although everything after "Space" is not clickable, and the "Popular" point is missing entirely.

![image](https://github.com/TheBLVD/mammoth/assets/65043391/fc11caee-89a4-45d8-9c5c-c65c8060c1ce)

**Comment by derspyy** [comment]
seems like the "Popular" link shows a card under the post, which is why it's missing. every link after that does not work.

![image](https://github.com/TheBLVD/mammoth/assets/65043391/8a216e63-9c57-46d7-b24f-b01d560c4960)

**Comment by derspyy** [comment]
this can possibly be closed since the new issue is unrelated to the whole html stuff.

**Comment by Mings-01** [comment]
I'm not sure what you mean, there is not one link that works! On my iPhone there are no links for any of the options

**Comment by derspyy** [comment]
oh this is 2.4 stuff. almost coming along
