### ISSUE TITLE
App keeps freezing when opened

### ISSUE THREAD

**Issue by Imzxhir** [TheBLVD/mammoth#307]
### Describe the bug

Mammoth keeps freezing when opening the app but, I am not sure why. I have a rough idea of why it is crashing.

I think it is because it is trying to load a really long tweet as seen in the screenshot below but fails and freezes the app instead.

The tweet that it is trying to load is this: https://blobfox.coffee/@Ember/111232504254769735

### To Reproduce

1. Open the tweet linked in the description
2. Your app should freeze

### Expected behaviour

The app should not be freezing when opened and loading that tweet.

### Screenshots

![IMG_0301](https://github.com/TheBLVD/mammoth/assets/98621617/0960d2ea-957c-444e-b19d-72458af4bf7b)

### Instance address

blobfox.coffee

### Device

iPhone 12

### OS

iOS 17.2.1

### Version

2.4.2

**Comment by bvon** [comment]
Thank you for reporting! This issue is likely resolved in Build 377, but will continue testing before closing this ticket.

**Comment by Imzxhir** [comment]
Update on this issue: I updated to version 2.5 of Mammoth but, that did not fix the freezing issue and I had to re-download the app to fix it. I think the problem is that Mammoth is not able to handle really long tweets or polls like this (https://blobfox.coffee/@Ember/111232504254769735) and thus, causing the app to freeze when trying to load the post.
