### ISSUE TITLE
Timeline messages are squashed altogether and badly auto-reloads themselves

### ISSUE THREAD

**Issue by C-Duv** [TheBLVD/mammoth#55]
**Describe the bug**

Displayed timeline is buggy: messages disappears, are shrunk/squashed and/or re-appears as I scroll (even a few pixels) through my timeline.

It's fairly often but do not occurs for every message for every scroll movement.

**To Reproduce**

1. Display the timeline
2. Scroll a few (or many) pixels or messages

**Expected behavior**

Messages should be displayed nicely and stay visible.

**Screenshots**

A screenshot of the squashed messages:

![Mammoth - Timeline message bug 1](https://user-images.githubusercontent.com/1466273/223569740-853f1b0f-c3f5-43f9-b567-83d3f853f020.png)

Another screenshot of the squashed messages:

![Mammoth - Timeline message bug 2](https://user-images.githubusercontent.com/1466273/223569751-dc8de6bf-2dc0-47ca-80b8-5bf244737758.png)

Here is a video recording of me scrolling through my timeline:

https://user-images.githubusercontent.com/1466273/223569589-f560dd95-9126-4872-b51e-e7c871003b7b.mp4

**Smartphone:**

- Device: iPhone7
- OS: iOS 14.8.1
- Version: 1.1, build 119

**Additional context**

Installed the application on 2023-02-25 and it was working fairly fine (just some scrolling issues) until I updated it on 2023-03-05 and got this issue.

**Comment by C-Duv** [comment]
Update: If I am disconnected from the network the application behave just fine: smooth scroll and no squashing.

**Comment by C-Duv** [comment]
Update: Issue is still present on version 1.2, build 128.

**Comment by bdecrem** [comment]
in progress - internal ticket: mam-1090

**Comment by MissPurrple** [comment]
Hi @C-Duv 🦣 , 
Just wanted to let you know that in the latest version of Mammoth - version 1.4, we've addressed this issue. We think this is fixed now; you can update your app to make sure. Should you continue to see the problem, let us know & we will get right on it. Happy Tooting!

**Comment by C-Duv** [comment]
Unfortunately the bug is still there in version 1.4 build 145.
I've just noticed I could produce and send a debug log, I'll do that and reference this issue in the e-mail.
