### ISSUE TITLE
Timeline doesn't fetch all post since the last read/watched post

### ISSUE THREAD

**Issue by domiden** [TheBLVD/mammoth#58]
**Describe the bug**
If the timeline is automatically or manually updated, the timeline fetches only posts of the past 60 minutes instead of all posts since the last read/watched posts.

**To Reproduce**
Open timeline and manually refresh timeline if automatically refreshing settings isn't set.

**Expected behavior**
All posts are fetched since the last read/watched post, beginning with the oldest post, where up-scrolling reveals newer posts. 

**Screenshots**
Difficulty because the screen is too small.

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.3.1
 - Version: 1.1 (119)

**Comment by sdubinsky** [comment]
I've passed this along!

**Comment by chenew** [comment]
@sdubinsky I’ve also noticed my timeline being quiet and when comparing it with other apps, there seems to be missing gaps of posts.

I have my timeline settings set to fetch all posts.
![556A04AA-EFBB-48A9-8CDE-378739A7274F](https://user-images.githubusercontent.com/5931313/227708603-308785b4-0faf-4f8b-96d9-e6182f32b2aa.jpeg)

While researching this, I found other people reporting the same issue. https://mstdn.games/@BlueBlasphemy/110078353033766857

@domiden Thanks for the analysis on the 60 minutes observation. That makes sense now why Mammoth is able to fetch new posts so quickly if I don’t use the app for awhile whereas other apps load chunks and chunks of posts until the latest.

**Comment by GitPuffy** [comment]
Is there a way to vote on this issue so that it gets high priority from the developers?

I like Mammoth and if there was a way for it to fetch the missing timeline posts it would be great.  I do see for a brief, very brief maybe one second, "thing" that says "Load More" in the timeline between the newly fetched posts and the very much older posts.  It flashes so quickly that I am not able to press it to see what it does.  It shows up and then disappears. 

I was able to make a screen recording of it and have it attached to this comment.  

https://user-images.githubusercontent.com/16783602/227732334-4da88a25-4296-43db-91de-8a6e60d7ff22.mp4

**Comment by bdecrem** [comment]
just letting you all know that we have not forgotten about this. are looking at it again as part of Sprint 6 (the work on Mammoth 1.6)

**Comment by delusho** [comment]
Solved now v

**Comment by delusho** [comment]
?

**Comment by bdecrem** [comment]
hi @delusho we did a bunch of work on this for Mammoth 1.7 and fixed almost all cases of this, but it's possible this is still happening in a much more limited set of cases. For Mammoth 1.10 we are actually in the process of completely rewriting the main timeline, and all of this logic will be new, and hopefully bug free. I'm running the new timeline on TestFlight and it's pretty awesome so far!

**Comment by bvon** [comment]
This issue seems to be resolved in Mammoth 2.
